name: Run checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.head_commit.id }}
          fetch-depth: 0

#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 14

      - name: Enable Corepack
        run: corepack enable

      - name: Get yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('.github/workflows/**.yml') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Run commit message linter
        uses: wagoid/commitlint-github-action@v6

      - name: Run linter
        run: yarn lint

      - name: Run unit tests
        run: yarn test:unit

      - name: Run browser tests
        run: yarn test:browser

      - name: Semantic Release
        if: contains(github.ref, 'refs/heads/main')
        uses: cycjimmy/semantic-release-action@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
